### PR TITLE
Make it work

### PR DESCRIPTION
**Pull request by cnmozzie**
But still some difference that I still don't figure out why.

### CODE REVIEW

**Comment by yueyericardo** [comment]
Hey Weixuan,

Thanks!

But, the trick here is that, angular part of STO fuction for Carbon cannot be ignored, since Carbon has p orbital.

**Comment by cnmozzie** [comment]
Yes, so I followed [this thesis](https://www.aau.dk/digitalAssets/281/281541_speciale---applied-hartree-fock-methods.pdf). The key is to expand reciprocal distance in terms of spherical harmonics:
<a href="https://www.codecogs.com/eqnedit.php?latex=\frac{1}{r_{i&space;j}}=\sum_{l,&space;m}&space;\frac{4&space;\pi}{2&space;l&plus;1}&space;Y_{l&space;m}^{*}\left(\theta_{1},&space;\phi_{1}\right)&space;Y_{l&space;m}^{*}\left(\theta_{2},&space;\phi_{2}\right)&space;\frac{r_{\min&space;}^{l}}{r_{\max&space;}^{l&plus;1}}" target="_blank"></a>
Then the matrix elements may be expressed as
<a href="https://www.codecogs.com/eqnedit.php?latex=\begin{aligned}&space;J_{\mu&space;\lambda}^{i&space;j}=\sum&space;c_{i&space;\lambda}&space;c_{j&space;\lambda}&space;\sum_{l,&space;m}&space;\frac{4&space;\pi}{2&space;l&plus;1}&space;&\left\langle&space;Y_{l_{1},&space;m_{1}}\left|Y_{l&space;m}\left(\theta_{1},&space;\phi_{1}\right)\right|&space;Y_{l_{1},&space;m_{1}}\right\rangle&space;\\&space;&&space;\times\left\langle&space;Y_{l_{2},&space;m_{2}}\left|Y_{l&space;m}^{*}\left(\theta_{2},&space;\phi_{2}\right)\right|&space;Y_{l_{2},&space;m_{2}}\right\rangle&space;\mathbb{J}&space;\end{aligned}" target="_blank"></a>
where
<a href="https://www.codecogs.com/eqnedit.php?latex=\mathbb{J}=\int_{0}^{\infty}&space;\int_{0}^{\infty}&space;r_{1}^{n_1-1&plus;2}&space;r_{2}^{n_{2}-1&plus;2}&space;\mathrm{e}^{-\zeta_1&space;r_{1}}&space;\mathrm{e}^{-\zeta_2&space;r_{2}}&space;\frac{r_{\min&space;}^{l}}{r_{\max&space;}^{l&plus;1}}&space;d&space;r_{1}&space;d&space;r_{2}" target="_blank"></a>
Now we have separated the radius part and angular part, where the latter is easy to estimate and most of them are zero. For example, we only need to deal with l=0, l=1 and l=2 for p-p Coulomb and exchange terms.
Finally, thank you for sharing the code. After several days' searching, this is the only hartree-fork code I could understand.

Update: I have find the bug. I forget to pass updated Pp matrix to the energy calculation function. I've corrected it on my [fork](https://github.com/cnmozzie/hartree-fock/blob/master/Carbon.ipynb).

**Comment by yueyericardo** [comment]
Thanks!, Nice work!

Could you push the Carbon update to here, so I can merge this pr?

**Comment by cnmozzie** [comment]
> Thanks!, Nice work!
> 
> Could you push the Carbon update to here, so I can merge this pr?

Done. (I hope the code is clear because I don't have time to add comments.)

**Pull request merged**
